name: setup test lint
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: setup project
              run: make setup

            - name: run tests
              run: make test

            - name: run linter
              run: make lint
